### PR TITLE
Travis CI PHP 7.4, phpstan max analysis level

### PR DESCRIPTION
**Pull request by Jalle19**
Changes proposed in this pull request:

 * Run Travis CI on PHP 7.4
 * Make service setters fluent
 * Increase the phpstan analysis level to 7

### CODE REVIEW

**Comment by hugovk** [comment]
What's the reason to only send coverage to Coveralls for a single version? It should be able to combine multiple reports into one.

**Comment by Jalle19** [comment]
@hugovk I'm not 100% if it's the culprit but I think it's the reason why it sometimes says "Coverage decreased -0.02%" when you change the README for example.

**Comment by hugovk** [comment]
Coverage sometimes does funny things.

Can you remember a place where it happened recently?

(OK to go ahead with the change.)

**Comment by Jalle19** [comment]
@hugovk happened on lumen-elasticsearch all the time

**Comment by hugovk** [comment]
Thanks, it happened here: https://github.com/digiaonline/lumen-elasticsearch/pull/140

And it's clearly not combining results properly:

image

Only one production file was changed (and its tests), and it's at 100%:

image

Not entirely sure why that affects the end result, but limiting it to a single version keeps it simple and is probably good enough!

**Pull request merged**
