### PR TITLE
Refactor CorsServiceProvider to be compatible with Laravel

### PR DESCRIPTION
**Pull request by cniska**

### CODE REVIEW

**Comment by hugovk** [comment]
Unit tests are failing on the CI.

**Comment by cniska** [comment]
@hugovk the tests pass just fine, it's the CI funnel that is messed up.

**Review by q-hung — APPROVED** [review]
It looks good to me :D

**Comment by Jalle19** [comment]
@crisu83 the tests most definitely don't pass, at least not according to Travis CI.

**Comment by Jalle19** [comment]
@crisu83 seems the tests were already broken (no idea why), can you fix them?

**Comment by cniska** [comment]
Now the tests are fixed.

**Review by Jalle19 — APPROVED** [review]

**Pull request merged**
