### PR TITLE
Lumen v8 compatibility

### PR DESCRIPTION
**Pull request by cdinopol**
(Please read the [guidelines](.github/CONTRIBUTING.md) before creating PRs.)

Changes proposed in this pull request:

 * Add composer /illuminate/support for ^8.0

### CODE REVIEW

**Comment by hugovk** [comment]
@cdinopol `master` now has tests on PHP 8.0, please could you rebase to check tests still pass on 8.0? Thanks!

**Comment by ssi-anik** [comment]
No update yet!

**Comment by goodspeed666** [comment]
If possible, please merge to master quickly.
Thank you.

**Comment by cdinopol** [comment]
> @cdinopol `master` now has tests on PHP 8.0, please could you rebase to check tests still pass on 8.0? Thanks!

rebased with master and tested. all good. `(11 tests, 40 assertions):  [OK] No errors`

**Comment by Jalle19** [comment]
https://packagist.org/packages/nordsoftware/lumen-cors#3.4.0

**Pull request merged**
