### PR TITLE
Support for Lumen 7

### PR DESCRIPTION
**Pull request by ibpavlov**
(Please read the [guidelines](.github/CONTRIBUTING.md) before creating PRs.)

Changes proposed in this pull request:

 * Add composer /illuminate/support for ^7.0 

(There is no needed additional change)

### CODE REVIEW

**Review by Jalle19 — APPROVED** [review]

**Comment by Jalle19** [comment]
@hugovk

**Comment by hugovk** [comment]
Thanks!

@Jalle19 I've invited you back to have a write role on this repo, let me know if there's any others missing (probably all the `lumen-*`?).

**Comment by Jalle19** [comment]
Yup, thanks!

**Comment by ibpavlov** [comment]
Can you create a new Tag. I want to use a stable version with composer. Thanks.

**Comment by hugovk** [comment]
Tagged and released as 3.3.0: https://packagist.org/packages/nordsoftware/lumen-cors

Thanks!

**Pull request merged**
