### PR TITLE
Upgrade to PHP 7.1

### LINKED ISSUE #55: Bump minimum PHP version to 7.1
We're gonna have to bump the major version anyway so might as well go all in

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #55

### CODE REVIEW

**Comment by mathewrapid** [comment]
What about those who cannot update to 7.1 or newer?

You mention that one reason is to get rid of our own Exceptions. There seemed to be only one `Nord\Lumen\Cors\Exceptions\InvalidArgument`. What about sticking to 7.0 and using the standard `\InvalidArgumentException`?

But if there is noone who can't update past 7.0 then go for it.

**Comment by Jalle19** [comment]
@mathewrapid I was thinking that those who can't upgrade can keep using version 2.x. of this library

**Comment by Jalle19** [comment]
> You mention that one reason is to get rid of our own Exceptions. There seemed to be only one `Nord\Lumen\Cors\Exceptions\InvalidArgument`. What about sticking to 7.0 and using the standard `\InvalidArgumentException`?

I changed to \InvalidArgumentException in one case and implicit TypeError elsewhere by type-hinting methods. This is partly why I set PHP 7.1 as the target (for `?string` for example).

**Comment by mathewrapid** [comment]
What about https://github.com/digiaonline/lumen-cors/pull/54 ? This would leave 7.0 users without these changes or did I miss something?

**Comment by hugovk** [comment]
Yes, that would leave PHP 7.0 users without the #54 changes.

---

PHP 7.0 itself has been out of "active support" since 3 Dec 2017:

> A release that is being actively supported. Reported bugs and security issues are fixed and regular point releases are made.

It's now in "security support":

> A release that is supported for critical security issues only. Releases are only made on an as-needed basis.

But only until 3 Dec 2018, when it is fully EOL:

> A release that is no longer supported. Users of this release should upgrade as soon as possible, as they may be exposed to unpatched security vulnerabilities.

image

https://secure.php.net/supported-versions.php

---

If we follow PHP's lead, is #54 a critical security issue? If not, do we know of anyone who still really needs lumen-cors on 7.0? They should be upgrading to 7.1+ instead.

**Comment by cniska** [comment]
@Jalle19 I’m with you on this. I think we can require people to have PHP 7.1 to use the latest version. However, this breaks BC so we need a new major version when we release this. We should also keep the old master as a separate branch parallel to the new master for future bug fixes.

**Comment by hugovk** [comment]
Call the old master branch `2.x`, not something like `old_master` :)

But isn't the point of dropping support that we don't need to support it or make future bug fixes?

**Comment by cniska** [comment]
Yes, call it 2.x.

**Comment by Jalle19** [comment]
I think we can make branches later if needed, no point in keeping dangling branches around IMO.

**Pull request merged**
